# Generated by Django 3.1.5 on 2021-01-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mem_used', models.CharField(max_length=50)),
                ('men_free', models.CharField(max_length=50)),
                ('mem_total', models.CharField(max_length=50)),
            ],
        ),
    ]
