# Generated by Django 3.1.5 on 2021-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fail_name', models.CharField(max_length=50)),
                ('fail_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
